### ISSUE TITLE
Incorrect macro delimiter can cause syntax error in mangled code

### ISSUE THREAD

**Issue by Byron** [serde-rs/syntex#11] opened 2015-06-19 07:45 UTC
If code containing macros is mangled through syntex, the produced code can be syntactically incorrect. The following annotated code allows to reproduce the issue.

``` Rust
use std::io::{Write, stdout};

fn delimiter() {
    // this delimiter determines the one used in the macro that follows
    (
        write!(stdout(), "1").ok()
    );

    (
        // this is syntactically incorrect, but works as the delimiter 
        // is overridden by the enclosing parantheses
        write!{stdout(), "2"}.ok()
    );
}

fn delimiter_fail() {
    // Please read on - this is the workaround of the following problem
    (write!(stdout(), "3")).ok();

    // this doesn't work, as the delimiter used for the function is 
    // used in the macro as well.
    // The macro itself would be syntactically correct
    write!(stdout(), "4").ok()
}
```
# How to reproduce

You can easily reproduce the issue with the latest syntex, `v0.7.0`, and the [respective branch in my fork](https://github.com/Byron/rust-syntex/tree/reproduce-issue-11)

``` bash
$ git clone --branch reproduce-issue-11 https://github.com/Byron/rust-syntex
$ cd rust-syntex/tests/macro_delimiter
$ cargo build
```

which results in something like

```
/private/tmp/rust-syntex/tests/macro_delimiter/target/debug/build/macro_delimiter-42f6e97bf01f0821/out/lib.rs:8:35: 8:36 error: unexpected token: `.`
/private/tmp/rust-syntex/tests/macro_delimiter/target/debug/build/macro_delimiter-42f6e97bf01f0821/out/lib.rs:8     write!{stdout (  ) , "hello" }.ok()
```

**Comment by erickt** [comment] 2015-07-12 13:45
I wonder if this is due to rust macros not preserving the brace style. I've got a [patch](https://github.com/rust-lang/rust/pull/26089) that fixes it that I have yet to get landed upstream. It still needs a little work to get it in though.

**Comment by Byron** [comment] 2015-07-13 07:18
Thanks so much for looking in to this ! Macros in Rust seem to show their teeth, and I start to realize why the language maintainers are not too happy with them (despite their features and usefulness). The devil is in the details.

**Comment by dtolnay** [comment] 2016-06-11 03:28
Thanks for the detailed steps for reproducing the issue. I was able to reproduce it with Syntex 0.7.0 but not Syntex 0.34.0 so it was fixed upstream somewhere in between.

**Closed as completed by dtolnay** 2016-06-11 03:28 UTC
